global:
    scrape_interval:     15s
    evaluation_interval: 15s

rule_files:
    # - "first.rules"
    # - "second.rules"

scrape_configs:
    - job_name: node
      static_configs:
              - targets: ['node-exporter:9100']
    - job_name: docker
      static_configs:
              - targets: ['localhost:9323']

    - job_name: prometheus
      static_configs:
              - targets: ['localhost:9090']

    - job_name: nginx_oss_grp
      scrape_interval: 5s
      scrape_timeout: 5s
      static_configs:
              - targets: 
                  - exporter1:9113
                  - exporter2:9113
                  - exporter3:9113
                  - exporter4:9113
    - job_name: cadvisor
      static_configs: 
              - targets: ['cadvisor:8080']

